steps:
  - id: "Inicio"
    name: gcr.io/cloud-builders/git
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Autenticarse con GCP
        echo "Iniciado despliegue"
        echo "rama $BRANCH_NAME"
        echo "Repositorio: $REPO_NAME"
        echo "Commit: $COMMIT_SHA"

  - id: "Detectar carpeta modificada"
    name: gcr.io/cloud-builders/git
    entrypoint: sh
    args:
      - -c
      - |

        git fetch --unshallow 2>/dev/null || git fetch --all --tags

        # Verificar si el fetch funcionó
        if [ $? -ne 0 ]; then
          echo "Error al obtener el historial de Git."
          exit 1
        fi

        _PREV_COMMIT=$(git rev-parse "${COMMIT_SHA}~1" 2>/dev/null || echo "")

        echo "Commit actual: $COMMIT_SHA"
        echo "Commit previo : ${_PREV_COMMIT:-"N/A (primer commit/push)"}"

        
        # Obtenemos la lista completa de archivos cambiados
        echo "Obtenmos diferencias"
        _CHANGED_FILES=$(git diff --name-only $_PREV_COMMIT $COMMIT_SHA)
        echo "Archivos detectados por git diff:"
        echo "$_CHANGED_FILES"
        

        _MODIFIED_FOLDERS_LIST=$(echo "$_CHANGED_FILES" | grep "administrador-infra/" | cut -d'/' -f1-3 | sort | uniq)

        if [ -z "$_MODIFIED_FOLDERS_LIST" ]; then
          echo "No se encontraron cambios relevantes en administrador-infra/."
          echo "_MODIFIED_FOLDER=" >> /workspace/env.sh
        else
          echo "--- Carpetas modificadas encontradas ---"
          echo "$_MODIFIED_FOLDERS_LIST"
          echo "----------------------------------------"
          echo "_MODIFIED_FOLDER_LIST=\"$_MODIFIED_FOLDERS_LIST\"" >> /workspace/env.sh
        fi


  - id: "Desplegar Infraestructura"
    name: hashicorp/terraform:1.7.0
    entrypoint: sh
    args:
        - -c
        - |
          cd administrador-infra/terraform
          echo "====Ejecutando terraform===="
          terraform init -input=false

          echo "====Ejecutando plan===="
          terraform plan -out=tfplan

          echo "====Ejecutando apply===="
          terraform apply -auto-approve -state=tfplan
          echo "termino despliegue..."

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: "data-engineer-410822"